#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "images/goomber.h"
#include "images/Mario.h"
#include "images/luigio.h"
#include "images/MLtitle.h"
#include "images/battlebg2.h"
#include "images/spiny.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  INITPLAY,
  PLAY,
  WIN,
  LOSE,
};

struct luigi theluigi;
struct goomba goomba1;
struct goomba goomba2;
struct goomba goomba3;
int stompcounter;
char stomped[20];
int moveupdown;
int moverightleft;


int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      case START:
        waitForVBlank();
        drawFullScreenImageDMA(MLtitle);

        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          waitForVBlank();
          drawFullScreenImageDMA(battlebg2);
          drawImageDMA(50, 100, 25, 25, spiny);
          drawImageDMA(120, 90, 25, 25, spiny);
          //draw mario on other side of screen
          drawImageDMA(120, 210, 16, 32, Mario);
          state = INITPLAY;
        }
        break;
      case INITPLAY:
        
        theluigi.x = 0;
        theluigi.y = 0;
        theluigi.enemiesStomped = 0;
        goomba1.stomped = 0;
        goomba2.stomped = 0;
        goomba3.stomped = 0;
        stompcounter = 0;

        state = PLAY;
        
        break;
      case PLAY:
        //if keypress then move luigi coords
        moveupdown = 0;
        moverightleft = 0;
        if (KEY_DOWN(BUTTON_UP, currentButtons) && theluigi.y != 0) {
          theluigi.y -= 1;
          moveupdown += 1;
        }

        if (KEY_DOWN(BUTTON_DOWN, currentButtons) && theluigi.y != 124) {
          theluigi.y += 1;
          moveupdown -= 1;
        }

        if (KEY_DOWN(BUTTON_LEFT, currentButtons) && theluigi.x != 0) {
          theluigi.x -= 1;
          moverightleft += 1;
        }

        if (KEY_DOWN(BUTTON_RIGHT, currentButtons) && theluigi.x != 224) {
          theluigi.x += 1;
          moverightleft -= 1;
        }

        waitForVBlank();

        undrawImageDMA(theluigi.y + moveupdown, theluigi.x + moverightleft, 16, 36, battlebg2);

        snprintf(stomped, 20, "Goombas stomped: %d", stompcounter);

        if (goomba1.stomped == 0) {
          drawImageDMA(90, 50, 20, 24, goomber);
        }

        if (goomba2.stomped == 0) {
          drawImageDMA(130, 130, 20, 24, goomber);
        }

        if (goomba3.stomped == 0) {
          drawImageDMA(40, 200, 20, 24, goomber);
        }

        drawImageDMA(theluigi.y, theluigi.x, 16, 36, luigio);
        //draw luigi

        drawString(0, 65, &stomped[0], 0);
            
        //if collision, change goomba to stomped and add 1 to stomped counter
        if (((theluigi.y >= 14 && theluigi.y <= 75) && (theluigi.x >= 84 && theluigi.x <= 125)) || ((theluigi.y >= 88 && theluigi.y <= 145) && (theluigi.x >= 74 && theluigi.x <= 115))) {
          fillScreenDMA(0); //collision
          state = LOSE;
        } 
        else if ((theluigi.y >= 54 && theluigi.y <= 114) && (theluigi.x >= 34 && theluigi.x <= 70)) { //collision w goomba 1
          if (goomba1.stomped == 0) {
            goomba1.stomped = 1;
            stompcounter += 1;
            undrawImageDMA(90, 50, 20, 24, battlebg2);
            undrawImageDMA(0, 165, 10, 10, battlebg2);
          }

        } else if ((theluigi.y >= 94 && theluigi.y <= 154) && (theluigi.x >= 114 && theluigi.x <= 150)) { //collision w goomba 2
          if (goomba2.stomped == 0) {
            goomba2.stomped = 1;
            stompcounter += 1;
            undrawImageDMA(130, 130, 20, 24, battlebg2);
            undrawImageDMA(0, 165, 10, 10, battlebg2);
          }

        } else if ((theluigi.y >= 4 && theluigi.y <= 64) && (theluigi.x >= 184 && theluigi.x <= 220)) { //collision w goomba 3
          if (goomba3.stomped == 0) {
            goomba3.stomped = 1;
            stompcounter += 1;
            undrawImageDMA(40, 200, 20, 24, battlebg2);
            undrawImageDMA(0, 165, 10, 10, battlebg2);
          }

        } else if ((theluigi.y >= 84 && theluigi.y <= 152) && (theluigi.x >= 194 && theluigi.x <= 226)) { //collision w mario
          fillScreenDMA(0x7fff);
          state = WIN; // state = win if no collisions with enemies and collide with mario
        }


        //state = lose if collision with spiny
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          state = START;
        }
        break;
      case WIN:
        waitForVBlank();

        char win1[] = "You have succeeded.";
        char win2[] = "Press select to return to menu.";

        drawString(50, 65, &win1[0], 0);
        drawString(60, 20, &win2[0], 0);

        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          state = START;
        }

        break;
      case LOSE:
        waitForVBlank();

        char gameover[] = "Unfortunately,";
        char gameover2[] = "you have perished.";

        drawString(50, 65, &gameover[0], 0x7fff);
        drawString(60, 65, &gameover2[0], 0x7fff);

        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          state = START;
        }
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
